<?php include_once 'menu.phtml'; ?>
<h2>Управление пользователями</h2><br />
<a href="/admin/createUser">Добовить пользователя</a><br /><br />

<table border="1">
        <th>id</th>
        <th>Имя</th>
        <th>email</th>
        <th>Дата регистрации</th>
        <th></th>
        <th></th>

<?php $users = $this->users;
if ($users) :

    foreach ($users as $user) {?>

        <tr>
            <td><?=$user['id'];?></td>
            <td><?=$user['name'];?></td>
            <td><?=$user['email'];?></td>
            <td><?=$user['date_registration'];?></td>
            <td><a href="/admin/editUser?id=<?=$user['id'];?>">Редактировать</a> </td>
            <td><a href="/admin/deleteUser?id=<?=$user['id'];?>">Удалить</a> </td>
        </tr>

        <?php
    }
endif;
?>
</table>