<?php
    $data = $this->data;
?>
<?php include_once 'menu.phtml'; ?>
<form action="/user/register" method="post">
    <b>Регистрация пользователя:</b> <br />
    <font color="red">
    <?= $data['errorMessage'] ?? ''; ?><br />
    </font>
    Ввведите email: <input type="text" name="email" placeholder="email"><br />
    Ввведите name: <input type="text" name="name" placeholder="Ваше имя"><br />
    Введите пароль: <input type="password" name="password1" placeholder="пароль"><br />
    Введите пароль еще раз: <input type="password" name="password2" placeholder="пароль"><br />
    <input type="submit" value="Зарегистрироваться"><br />
</form>
