<?php
include_once 'menu.phtml';
/** @var \App\Model\User $user */
$user = $this->user;
if ($user): ?>
    <b>Ваш id:</b> <?= $user->id;?> <br />
    <b>Имя:</b> <?= $user->name;?> <br />
    <b>email:</b> <?= $user->email;?> <br />
    <b>Дата регистрации:</b> <?= $user->date_registration;?> <br />


<form action="/user/logout">
    <input type="submit" value="Выйти">
</form>
<?php else: ?>
Зарегистрируйтесь или войдите на сайт
<?php endif;?>
